<?php
$_cats = $this->getCatsCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_cats->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products cat-widz">

        <?php $_collectionSize = $_cats->count() ?>
        <?php $_columnCount = $column; ?>
        <?php $i = 0;
        foreach ($_cats as $_category): ?>
            <?php $category = Mage::getModel('catalog/category')->load($_category->getId()); ?>
            <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="products-grid">
            <?php endif ?>
            <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">

                <a href="<?php echo $category->getUrl() ?>"
                   title="<?php echo $this->stripTags($category->getName(), null, true) ?>" class="product-image"><img
                        src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$category->getThumbnail(); ?>"
                        width="135" height="135"
                        alt="<?php echo $this->stripTags($category->getName(), null, true) ?>"/></a>

                <h2 class="product-name">
                    <a href="<?php echo $category->getUrl() ?>"
                                            title="<?php echo $this->stripTags($category->getName(), null, true) ?>">
                        <?php echo $category->getName(); ?></a>
                </h2>

            </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
        <script
            type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>


    </div>
<?php endif; ?>
