<script>
var rootjt<?php echo $wzid; ?>;
jQuery(function() {
	jQuery("#wzid_<?php echo $wzid; ?> .scrollable").scrollable({circular: true}).autoscroll({ autoplay: true, interval: 7000, autopause: true });
    rootjt<?php echo $wzid; ?> = jQuery("#wzid_<?php echo $wzid; ?> .scrollable").data('scrollable');
});
</script>
<?php
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if ($_productCollection->count()): ?>

    <div class="page-title category-title link">
        <?php $cat_id = $this->getCatId();
        if($cat_id){
            $category = Mage::getModel('catalog/category')->load($cat_id); ?>
            <h1><a href="<?php echo $category->getUrl(); ?>"><?php echo $wlabel; ?></a></h1>
            <a class="view-all" href="<?php echo $category->getUrl(); ?>">View All &rsaquo;</a>
        <?php }else{ ?>
            <h1><?php echo $wlabel; ?></h1>
       <?php  } ?>
    </div>

    <div class="content new-callout" id="wzid_<?php echo $wzid; ?>">

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $column; ?>

        <div class="category-view niwidz">
            <div class="category-products scrollable">
                <div class="category-products items">
                    <?php $i = 0;
                    foreach ($_productCollection as $_product): ?>

                        <?php if ($i % $_columnCount == 0): ?>
                            <div>
                            <ul class="products-grid">
                        <?php endif ?>
                        <?php $i++; ?>

                        <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">

                            <?php if ($this->helper('callouts')->getIsNew($_product)) : ?>
                                <div class="new-product-callout">New</div>
                            <?php endif ?>
                            <?php if ($_product->getSpecialPrice()) : ?>
                                <div class="sale-product-callout">On Sale</div>
                            <?php endif ?>

                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                               class="product-image"><img
                                    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"
                                    width="135" height="135"
                                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>

                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                        title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                            </h2>
                            <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            <?php $cfp = ($_product->getCallForPrice()) ? $_product->getCallForPrice() : Mage::getModel('catalog/product')->loadByAttribute('sku', $_product->getSku())->getCallForPrice(); ?>
                            <?php if ($_product->isSaleable() && !$cfp): ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <div class="actions">
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                            class="button btn-cart"
                                            onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')">
                                        <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                </div>
                            <?php else: ?>
                                <div class="price-box"><span
                                        class="price"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('call_for_price')->toHTML(); ?></span>
                                </div>
                                <div class="actions">
                                    <button type="button" title="<?php echo $this->__('See Details') ?>"
                                            class="button btn-cart details"
                                            onclick="setLocation('<?php echo $_product->getProductUrl() ?>')">
                                        <span><span><?php echo $this->__('See Details') ?></span></span></button>
                                </div>
                            <?php endif; ?>
                        </li>

                        <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                            </ul>
                            </div>
                        <?php endif ?>

                    <?php endforeach ?>
                </div>
            </div>
            <div class="scroll-nav">
                <a class="prev browse left">prev</a>
                <a class="next browse right">next</a>
            </div>
        </div>
        <a type="button" onClick="rootjt<?php echo $wzid; ?>.play()">Play</a>
        <a type="button" onClick="rootjt<?php echo $wzid; ?>.pause()">Pause</a>
    </div>

<?php endif; ?>

