<?php $amazoncore = Mage::getModel('amazonimport/amazonimport'); ?>
<div class="entry-edit">
<div class="fieldset " id="group_fields4">To begin, please press
'Clone' below. Magento will run through all settings on the selected marketplace and clone them onto your current marketplace. This may take a few minutes.</div>
</div>

<div class="entry-edit" id="clonebuttonzone"
	name="clonebuttonzone" style="display: block;">
<div class="entry-edit-head">
<h4 class="icon-head head-edit-form fieldset-legend">Commence Cloning</h4>
<div class="form-buttons"></div>
</div>
<div class="fieldset " id="group_fields4">
<div class="hor-scroll">
<div id="displaynode">
<center>
<button id="clonebutton" type="button" class="scalable "
	onclick="startclone();" style=""><span>Clone</span></button>
</center>
</div>
</div>
</div>
</div>


<div class="entry-edit" id="cloneprep" name="cloneprep"
	style="display: none;">
<div class="entry-edit-head">
<h4 class="icon-head head-edit-form fieldset-legend">Cloning settings</h4>
<div class="form-buttons"></div>
</div>
<div class="fieldset " id="group_fields4">
<div class="hor-scroll">
<div id="displaynode">
<table cellspacing="0" class="form-list">
	<tbody>

		<tr>
			<td class="label"><label for="color">Current Progress</label></td>
			<td class="value">
			<div style="width: 200px; border: 1px solid #999999; float: left;">
			<div id="currentprogress" style="width: 0%; background: green;">&nbsp;</div>
			</div>
			&nbsp; <span id="progresspercent">0%</span> <span
				id="clone_indicator" class="autocomplete-indicator"> <img
				src="<?php echo $amazoncore->getSkinUrl(); ?>skin/adminhtml/default/default/images/ajax-loader.gif"
				alt="Loading..." class="v-middle"> </span></td>
			<td class="scope-label"></td>
			<td><small>&nbsp;</small></td>
		</tr>

		<tr>
			<td class="label"><label for="color">Estimated Time
			Remaining</label></td>
			<td class="value"><span id="timeleft">Estimating time
			required...</span></td>
			<td class="scope-label"></td>
			<td><small>&nbsp;</small></td>
		</tr>

	</tbody>
</table>
</div>
</div>
</div></div>


<div class="entry-edit" id="cloneer" name="cloneer"
	style="display: none;">
<div class="entry-edit-head">
<h4 class="icon-head head-edit-form fieldset-legend">Cloning Complete</h4>
<div class="form-buttons"></div>
</div>
<div class="fieldset " id="group_fields4">
<div class="hor-scroll">
<div id="displaynode">
	Cloning has completed successfully. We recommend that you now click 'Back' above to view the changes in the grid view.
</div>
</div>
</div>
</div>

<form
	action="<?php echo $amazoncore->getRootUrl(); ?>amazonimport/bulkclonehelper/variations/cachebuster/<?php echo time(); ?>"
	method="POST" id="prepareclonefile" name="prepareclonefile"
	target="iframeclone"><input type="hidden" name="form_key"
	id="form_key"
	value="<?=Mage::getSingleton('core/session')->getFormKey() ?>" /> <input
	type="hidden" name="regenerate" id="regenerate" value="0" /> <input
	type="hidden" name="cloningfrom" id="cloningfrom" value="0" /></form>

<iframe src="about:blank" id="iframeclone" name="iframeclone"
	style="width: 1px; height: 1px;" frameborder="0"></iframe> <script
	type="text/javascript">
	
			function startclone() {
				$('regenerate').value = "1";
				$('cloningfrom').value = $('clone_from').options[$('clone_from').selectedIndex].value;
				Effect.Fade('clonebuttonzone');
				Effect.Appear('cloneprep');
				$('prepareclonefile').submit();
				$('regenerate').value = "0";
			}

			function updatestatus(percentval,alttext,timeleft){
				$('timeleft').innerHTML = timeleft;
				$('progresspercent').innerHTML = percentval;
				$('currentprogress').morph('width:'+percentval+';background:green;');
				$('currentprogress').alt = alttext;
				$('currentprogress').title = alttext;
				<?php echo $amazoncore->browserCheckForReloader('prepareclonefile'); ?>
			}

			function goclonecomplete(){
				Effect.Fade('cloneprep');
				Effect.Appear('cloneer');
			}

			function goreclone(){
				<?php echo $amazoncore->browserCheckForReloader('prepareclonefile'); ?>
			}

			function goregenerate(){
				$('regenerate').value = "1";
				$('prepareclonefile').submit();
				Effect.Fade('cloneer');
				Effect.Appear('cloneprep');
				$('regenerate').value = "0";
			}
			
        </script>