<div class="entry-edit">
<div class="fieldset " id="group_fields4">This tool is designed to assist you in copying field mappings from another marketplace on the current marketplace..<br />
For example, if you have set up field mapping for Amazon UK and wish to start selling on Amazon USA, you may use this tool to mirror your settings automatically.<br /><br />

To begin, please review the details below. All existing settings of this type on the current marketplace setup will be overwritten.<br/>
Next, proceed to 'Select Marketplace'.</div>
</div>

<div class="entry-edit" id="downloadbuttonzone"
	name="downloadbuttonzone" style="display: block;">
<div class="entry-edit-head">
<h4 class="icon-head head-edit-form fieldset-legend">The following settings will be cloned</h4>
<div class="form-buttons"></div>
</div>
<div class="fieldset " id="group_fields4">
<div class="hor-scroll">
<div id="displaynode">
     - Variation Themes
</div>
</div>
</div>
</div>
