<h4>Help Completing CSV File</h4>

<div class="entry-edit">
<div class="fieldset " id="group_fields4">
Now that you have downloaded the CSV file, please open it in your favourite spreadsheet software (for example OpenOffice, Numbers or Excel). Once open, navigate to row 2. Row 1 contains headers and therefore you will not need to update this row.<br/><br/>
Columns A, B, H, I and J of this file are for reference only and are designed to help you to understand which product this row relates to. Column C is a separator line for reference only.</div>
</div>

<div class="entry-edit">
<div class="fieldset " id="group_fields4">
<b>Column D</b> allows you to set whether or not you would like the software to publish your product onto Amazon. Please enter <b>1</b> or <b>yes</b> if you would like to publish this product onto Amazon once setup is complete, or enter <b>0</b> or <b>no</b> if not.<br/><br/>

<b>Please note that setting the above value to 0 or no will not remove your product from Amazon Seller Central; you must do this yourself manually for security reasons.</b><br /><br />

<b>Column E</b> allows you to specify whether you wish to allow the software to search for this product on Amazon or not. If you would like this search to take place, please enter <b>search</b>, <b>auto</b> or <b>quick</b>. If you wish to skip past searching Amazon for your product, enter <b>skip</b> or <b>manual</b>. We have allowed multiple words to ensure compatibility with previous versions of this software which referred to these options differently.<br /><br />

<b>Column F</b> allows you to specify whether you would like to use Competitive Repricing with this product. Competitive Repricing checks competitor prices on Amazon to ensure that you remain the cheapest for a product within <i>strict</i> boundaries which you set. If you would like to enable this feature, please enable <b>yes</b> or <b>1</b>, otherwise to disable repricing, please enter <b>no</b>.<br /><br />

<b>Column G</b> is optional and allows you to set the minimum price which Competitive Repricing may reduce your price to. If set to 0 or left blank, the software will automatically use your product price to prevent items being sold for less than planned.<br /><br />
</div>
</div>
