<?php $amazoncore = Mage::getModel('amazonimport/amazonimport'); ?>

<div class="entry-edit" id="automatchsettings" name="automatchsettings"	style="display:block;"> 
<div class="entry-edit">
	<div class="fieldset " id="group_fields4">
	<p class="grand-total"><b>Help Tip: Find Products on Amazon wizard</b></p> Now that you have selected the 
	products which you would like to have Magento publish to your Amazon account, you can use this wizard 
	to search Amazon for your products. This will reduce the time taken to add your products 
	to Amazon, as in one click of a button your product could be set up if they have already been added by another seller.<br /><br />
	
	To begin, please review the 'Search Settings' below. This allows you to specify product 
	attributes you wish to use when searching for your products on Amazon. We recommend using a field containing a manufacturer product ID, but if this is unavailable Name may give positive results. You can select more than one attribute - if you do this, the wizard will try each attribute in order and until search results are found. Once you are happy with the settings selected, please press 'Begin Search' to start the interactive search process.							
	</div>
</div>

<div class="entry-edit-head">
<h4 class="icon-head head-edit-form fieldset-legend">Search Settings</h4>
<div class="form-buttons"></div>
</div>
<div class="fieldset " id="group_fields4">
<div class="hor-scroll">
<div id="displaynode">
 <b>Please review the settings below, then click 'Begin Search' to start searching on Amazon.</b>
 <form action="<?php echo Mage::getModel('amazonimport/amazonimport')->getRootUrl(); ?>amazonimport/automatch/startautomatch/" target="automatchIframe" name="ignition" method="POST">
 <table cellspacing="0" class="form-list">
	<tbody>

		<tr>
			<td class="label"><label for="color">Search using these attributes:</label></td>
			<td class="value">	<select name="attributes[]" multiple size="8" style="width:450px;">
									<?php echo Mage::getModel('amazonimport/autoengine')->attribout('one'); ?>
								</select>
								<small>To select multiple attributes to search with, press ctrl + click (Mac users: Command + Click)</small></td>
			<input type="hidden" name="form_key" id="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /> </td>
		</tr>
		<tr>
		<?php
		
		    $country = Mage::getModel('amazonimport/amazonimport')->loadSessionValue('camiloo_amazon_automatch_marketplace');
					
			if(!isset($_SESSION['qsw_'.$country.'_merchantid'])){
				$_SESSION['qsw_'.$country.'_merchantid'] = "";
			}
		
		?>
			<td class="label"><label for="color">Only show items sold by Seller:</label></td>
			<td class="value"><input type="text" name="merchantid" id="merchantid" value="<?php echo $_SESSION['qsw_'.$country.'_merchantid']; ?>" /><br />
								<small><b>Enter Merchant ID</b>. To only show results sold by Amazon, enter the ID for your country:<br />
								 .com - A2R2RITDJNW1Q6<br />
								 .co.uk - A3P5ROKL5A1OLE<br />
								 .de - A3JWKAKR8XB7XF<br />
								 .fr - A1X6FK5RDHNB96</small></td>
		</tr>
		<tr>
			<td class="label"><label for="color">If only one match is found:</label></td>
			<td class="value">
					<?php
					
					if(!isset($_SESSION['qsw_'.$country.'_autoapprove'])){
						$_SESSION['qsw_'.$country.'_autoapprove'] = 1;
					}
					if(!isset($_SESSION['qsw_'.$country.'_autoskip'])){
						$_SESSION['qsw_'.$country.'_autoskip'] = 1;
					}
					if(!isset($_SESSION['qsw_'.$country.'_ignoreexisting'])){
						$_SESSION['qsw_'.$country.'_ignoreexisting'] = 1;
					}
							
					echo '<input type="checkbox" name="autoapprove" value="1" ';
					if($_SESSION['qsw_'.$country.'_autoapprove'] == 1){
							echo 'checked="checked"';
					}
					
					echo '/> Automatically accept the match and continue<br />';
					
					?>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="color">If no matches are found:</label></td>
			<td class="value">
			<?php
			
			echo '<input type="checkbox" name="autoskip" value="1" onchange="if(this.checked){ document.getElementById(\'changetype\').disabled = false; }else{ document.getElementById(\'changetype\').disabled = \'disabled\'; document.getElementById(\'changetype\').checked = \'\';  }" ';
					if(isset($_SESSION['qsw_'.$country.'_autoskip'])){
						if($_SESSION['qsw_'.$country.'_autoskip'] == 1){
							echo 'checked="checked"';
						}
					}
					echo '/> Automatically skip to the next product<br />
			<input type="checkbox" name="changetype" id="changetype" value="1" ';
					if(isset($_SESSION['qsw_'.$country.'_changetype'])){
						if(isset($_SESSION['qsw_'.$country.'_changetype']) == 1 ){
							if(isset($_SESSION['qsw_'.$country.'_autoskip'])){
								if($_SESSION['qsw_'.$country.'_autoskip'] == 1){
									echo 'checked="checked"';
								}else{
									echo 'disabled="disabled"';
								}
							}else{
									echo 'disabled="disabled"';
							}
						}else{
									echo 'disabled="disabled"';
						}
					}else{
									echo 'disabled="disabled"';
					}
					echo '/> Change setup type to Manual';
			?></td>
			
		</tr>
		<tr>
			<td class="label"><label for="color">If product is already matched:</label></td>
			<td class="value">
			<?php
			
					echo '<input type="checkbox" name="ignoreexisting" value="1"  ';
					if(isset($_SESSION['qsw_'.$country.'_ignoreexisting'])){
						if($_SESSION['qsw_'.$country.'_ignoreexisting'] == 1){
						echo 'checked="checked"';
						}
					}
					echo '/> Allow me to choose a new match';
					
			?>		
			</td> 
		</tr>		
		<tr>
			<td class="label"><label for="color">Search Mode:</label></td>
			<td class="value">
			<?php
			
					echo '<input type="radio" name="searchmode" value="1"  ';
					if(isset($_SESSION['qsw_'.$country.'_searchmode'])){
						if($_SESSION['qsw_'.$country.'_searchmode'] != 2){
						echo 'checked="checked"';
						}
					}else{
						echo 'checked="checked"';
					}
					echo '/> <b>Search without checking for variations</b><br />
					      &nbsp;&nbsp;&nbsp; <i>Recommended if you do not have configurable products.</i> <br /><br />';
					
					echo '<input type="radio" name="searchmode" value="2"  ';
					if(isset($_SESSION['qsw_'.$country.'_searchmode'])){
						if($_SESSION['qsw_'.$country.'_searchmode'] == 2){
						echo 'checked="checked"';
						}
					}
					echo '/> <b>Check each search result for variations</b><br />
					      &nbsp;&nbsp;&nbsp; <i>Slower, but vital for finding configurable product children</i> <br />';
					
			?>		
			</td> 
		</tr>		
		<tr>
			<td></td>
			<td class="label" colspan="3"><button type="submit" class="scalable" onclick="$('ignition-indicator').style.display ='block';">Begin Search Process</button>
			<span id="ignition-indicator" class="ignition-indicator" style="clear:none; float:left; display:none;"><img src="<?php echo $amazoncore->getSkinUrl(); ?>skin/adminhtml/default/default/images/ajax-loader.gif" alt="Loading..." class="v-middle"> </span>
			</td>
		</tr>


	</tbody>
</table>
</form>
</div>
</div>
</div>
</div>


<div class="entry-edit" id="automatcher" name="automatcher"	style="display:none;">
	<div class="entry-edit">
	<div class="fieldset " id="group_fields4">
	<p class="grand-total"><b>Help Tip: Interactive Search Results</b></p> 
	On this screen, you will periodically be shown a list of search results when the wizard has found 
	a match for your products. If the system has found more than one result or you do not enable 
	automatic approval of single match results, you must click on the large orange button next to 
	the search result which matches your product. You can preview both the product listing on your 
	own website (shown in the darker grey area of the window) or click 'See all product details' to 
	see the product on Amazon.<br /><br />
	
	In the event that none of the search results returned match your product, click 'Skip This Product' 
	to move onto the next product in your queue, and you may search for this product again using a different product attribute later. If you feel confident the product is not on Amazon, select 'Skip and change to Manual Setup'. The product can then be submitted using the Review Products menu item.</div>
</div>
	
	
	
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Interactive Search Results</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset " id="group_fields4" style="padding:0px !important;">
		<div class="hor-scroll">
			<div id="displaynode">

				<div class="fieldset " id="searchresultoutputpane" style="border:0px;height:600px;margin-bottom: 0;background:#FFFFFF;overflow:auto;">
				</div>
	
				<div style="height:80px;padding:20px;">
					<table width="100%" border="0" cellspacing="0" cellpadding="5">
					  <tr>
						<td width="65"><img src="" id="currentProductImage" height="50" width="50" /></td>
						<td><b>Name:</b> <span id="currentProductName"></span><br />
							<b>SKU:</b> <span id="currentProductSKU"></span><br />
							<b>ID:</b> <span id="currentProductID"></span><br /></td>
						<td width="300px;align="right"><span id="progresspercent" style="float:right;">&nbsp;0%</span>&nbsp;<div style="overflow:hidden;width: 200px; height:10px; border: 1px solid #999999; float: right;">
							<div id="currentprogress" style="width: 0%; background: green;">&nbsp;</div>
							</div>&nbsp;
							<br /><span id="currentstatus" style="float:right; clear:both;"><b>Status:</b> Awaiting user selection</span><br />
						<button class="scalable" id="automatchbutton" name="button" type="button" onclick="skipProduct();" style="display:none">Skip this product</button><br />
						<button class="scalable" id="automatchbutton_two" name="button" type="button" onclick="skipAndMoveToManualProduct();" style="display:none">Skip and change to Advanced Setup</button></td>
					  </tr>
					</table>
				</div>
				<div class="entry-edit-head">
					<h4 class="icon-head head-edit-form fieldset-legend">Progress: <span id="footerProgressCount">1</span> of <span id="footerProgressOf">2084</span> products processed. <span id="footerProgressMatches">1</span> matches saved.</h4>
					<div class="form-buttons"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="entry-edit" id="automatcherresults" name="automatcherresults" style="display: none;">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Search Complete</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset " id="group_fields4">
		<div class="hor-scroll">
			<div id="displaynode">
				The search wizard has completed. Matches were found for <span id="matchesfound"></span> of the <span id="selectedcount"></span> products you have selected to list on Amazon. Please now continue to the Review Products screen to complete setup of your products.
				
			
			</div>
		</div>
	</div>
</div>


<form action="<?php echo $amazoncore->getRootUrl(); ?>amazonimport/automatch/fetch/cachebuster/<?php echo time(); ?>" method="POST" id="fetchform" name="fetchform" target="automatchIframe">
		<input type="hidden" name="form_key" id="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /> 
		<input type="hidden" name="fetchproductid" id="fetchproductid" value="0" /> 
		<input type="hidden" name="fetchproductcount" id="fetchproductcount" value="1" /> 
</form>


<form action="<?php echo $amazoncore->getRootUrl(); ?>amazonimport/automatch/saveMatch/cachebuster/<?php echo time(); ?>" method="POST" id="saveMatchSelectionform" name="saveMatchSelectionform" target="automatchIframe">
		<input type="hidden" name="form_key" id="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /> 
		<input type="hidden" name="saveproductid" id="saveproductid" value="0" /> 
		<input type="hidden" name="chosenasin" id="chosenasin" value="0" />
		<input type="hidden" name="saveProgressCount" id="saveProgressCount" value="1" />
		<input type="hidden" name="saveProgressMatches" id="saveProgressMatches" value="0" />
		<input type="hidden" name="saveproductcount" id="saveproductcount" value="0" />
		<input type="hidden" name="saveresultsize" id="saveresultsize" value="0" />
		<input type="hidden" name="savepercentage" id="savepercentage" value="0" />
</form>


	<script type="text/javascript">
	
			function skipProduct(){
				$('automatchbutton').style.display = 'none';
				$('automatchbutton_two').style.display = 'none';
				$('saveMatchSelectionform').submit();
				$('searchresultoutputpane').innerHTML = '';
			}
			
			function skipAndMoveToManualProduct(){
				$('automatchbutton').style.display = 'none';
				$('automatchbutton_two').style.display = 'none';
				$('chosenasin').value = 'SKIP_MOVE_TO_MANUAL';
				$('searchresultoutputpane').innerHTML = '';
				$('saveMatchSelectionform').submit();
			}
			
			function fetchProduct(){
				$('searchresultoutputpane').innerHTML = '';
				$('fetchform').submit();
			}
	
			function itemSelected(asinvalue){
				$('automatchbutton').style.display = 'none';
				$('automatchbutton_two').style.display = 'none';
				$('chosenasin').value = asinvalue;
				$('searchresultoutputpane').innerHTML = '';
				$('saveMatchSelectionform').submit();
			}
	
	</script>
		
		<iframe name="automatchIframe" id="automatchIframe" style="" frameborder="0"></iframe>
 