<div class="entry-edit">
<div class="fieldset " id="group_fields4">To begin, please review the settings below. These settings control what actions you would like the module to take when a matching product is found on Amazon. For large catalogues we strongly recommend 'Automatically approve matches' as this will greatly reduce the setup time required for your products.</div>
</div>


<div class="entry-edit" id="downloadbuttonzone"
	name="downloadbuttonzone" style="display: block;">
<div class="entry-edit-head">
<h4 class="icon-head head-edit-form fieldset-legend">Quick Setup Settings</h4>
<div class="form-buttons"></div>
</div>
<div class="fieldset " id="group_fields4">
<div class="hor-scroll">
<div id="displaynode">
	<b>When a matching product is found on Amazon...</b><br/>
     <input type="radio" value="auto" id="approve_auto" name="approve" checked="checked" /> Automatically approve the match.<br />
     <input type="radio" value="manual" id="approve_manual" name="approve" /> Do not automatically approve the match; I will manually approve each match found.<br /><br />
    
    <b>If a previous automatch run has found a product on Amazon...</b><br/>
     <input type="radio" value="no" id="repeat_no" name="repeat" checked="checked" /> Skip this product.<br />
     <input type="radio" value="yes" id="repeat_yes" name="repeat"/> Repeat the automatch process anyway.<br />
 
</div>
</div>
</div>
</div>
