<?php $amazoncore = Mage::getModel('amazonimport/amazonimport'); ?>
 
<div class="entry-edit">
<div class="fieldset " id="group_fields4">
<p class="grand-total"><b>Help Tip: The Find Products on Amazon Wizard</b></p> 

The grid below lists the products you have selected for Find Products on Amazon. It is these products which will be searched for on Amazon according
to your selected criteria.

<br /><br />

</div>
</div>

<div class="entry-edit" id="automatchsettings" name="automatchsettings"	style="display:block;">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Search Settings</h4>
		<div class="form-buttons"></div>
	</div>
	<div class="fieldset " id="group_fields4">
		<div class="hor-scroll">
			<div id="displaynode">
			
			</div>
		</div>
	</div>

</div>

 