<div class="sales-force-contact-us" id="postComment">
<!--  ----------------------------------------------------------------------  -->
<!--  NOTE: Please add the following <META> element to your page <HEAD>.      -->
<!--  If necessary, please modify the charset parameter to specify the        -->
<!--  character set of your HTML page.                                        -->
<!--  ----------------------------------------------------------------------  -->
<!-- <META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8"> -->
<!--  ----------------------------------------------------------------------  -->
<!--  NOTE: Please add the following <FORM> element to your page.             -->
<!--  ----------------------------------------------------------------------  -->
<form action="https://www.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8" method="POST">
<input type=hidden name="orgid" value="00D600000007Dvw">
<input type=hidden name="retURL" value="http://www.primelec.com">
<!--  ----------------------------------------------------------------------  -->
<!--  NOTE: These fields are optional debugging elements.  Please uncomment   -->
<!--  these lines if you wish to test in debug mode.                          -->
<!--  <input type="hidden" name="debug" value=1>                              -->
<!--  <input type="hidden" name="debugEmail" value="alapeter@primelec.com">   -->
<!--  ----------------------------------------------------------------------  -->
<label for="name">Contact Name</label><input  id="name" maxlength="80" name="name" size="20" type="text" /><br>
<label for="email">Email</label><input  id="email" maxlength="80" name="email" size="20" type="text" /><br>
<label for="phone">Phone</label><input  id="phone" maxlength="40" name="phone" size="20" type="text" /><br>
<label for="type">Type</label><select  id="type" name="type"><option value="">--None--</option><option value="General Question">General Question</option>
<option value="Bulk Purchase">Bulk Purchase</option>
<option value="Item Question">Item Question</option>
<option value="Checkout Problem">Checkout Problem</option>
<option value="Return">Return</option>
<option value="Replacement Request">Replacement Request</option>
<option value="Stock Check">Stock Check</option>
<option value="Shipping Issue">Shipping Issue</option>
<option value="Customer Service Issue">Customer Service Issue</option>
</select><br>
<label for="subject">Subject</label><input  id="subject" maxlength="80" name="subject" size="20" type="text" /><br>
<label for="description">Description</label><textarea name="description"></textarea><br>
<input type="hidden"  id="external" name="external" value="1" /><br>


<div class="button-set">
					<button type="submit" class="button"><span><span>Submit</span></span></button>
				</div>

</form>
</div>