
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <span class="amount"><?php echo $this->__('(%d)', $this->getReviewsCount()) ?></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <?php /*<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>*/ ?>
<?php endif; ?>
