<?php echo "toy aca"; ?>
<?php if($this->isEmailDirectEnabled($this->getCustomer()->getStoreId())): ?>
	<?php if($this->getSubscribedAdditionalLists()): ?>
	    <div class="box-title">
	        <h3><?php echo $this->__('Additional Newsletters Lists') ?></h3>
	    </div>
	    <div class="box-content">
		<?php foreach ($this->getSubscribedAdditionalLists() as $_list): ?>
			<?php if($_list->getIsSubscribed()): ?>
				<p style="margin-bottom:0px;"><?php echo $this->htmlEscape($_list->getName()) ?></p>
			<?php endif; ?>
		<?php endforeach;?>
		</div>
	<?php endif;?>
	<img alt="Powered By EmailDirect" src="<?php echo $this->getSkinUrl('emaildirect/images/mailchimp_tile.png') ?>" style="float:right;"/>
<?php endif;?>

