<?php

$lists       = $this->getLists();
$myLists     = $this->getSubscribedLists();
$generalList = $this->getGeneralList();

?>
<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription'); ?></h1>
</div>
<form action="<?php echo $this->getUrl('emaildirect/customer_account/saveadditional'); ?>" name="emaildirect_additional" id="emaildirect-additional" method="post">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<ul class="emaildirect-additional-lists">
			<!-- General Subscription -->
			<li class="listdata"><?php echo 'General Subscription : '.$this->publicationLabel($generalList); ?>
			<!-- General Subscription -->
			<!-- Additional Lists -->
			<?php
				foreach($lists as $list):
					//$igroups = $list['interest_groupings'];
			?>

				<li class="listdata"><?php echo $this->listLabel($generalList,$list); ?>
				</li>

			<?php endforeach; ?>
			<!-- Additional Lists -->

		</ul>
	</div>
	<input type="hidden" name="state" value="" id="form-state" />
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
	document.observe("dom:loaded", function() {
		removeManageNewsletter();
		$$('.emaildirect-publication-subscriber').first().observe('change', function(){
			var groupings = $$('.emaildirect-list-subscriber');
			
			if(groupings){
				if(this.checked){
					groupings.each(function(index, item){
						
						if(this.value != index.value){
							index.removeAttribute('disabled');
						}
						
					}.bind(this));
				}else{
					groupings.each(function(index, item){
						if(this.value != index.value){
							index.writeAttribute('disabled', 'disabled');
						}
						
					}.bind(this));							
				}
			}
		});		
		$('form-state').writeAttribute('value', $('emaildirect-additional').serialize());

	});
</script>
