<?php if(Mage::getStoreConfig('amazonint/general/hide_help_tips') == 0){ ?>
<div class="entry-edit">
        <fieldset id="my-fieldset">		
		<p class="grand-total"><b>Help Tip: Categorising your products.</b></p>
		It is now time to categorise the products which were not found automatically by the Find Products on Amazon Wizard. To categorise a product, click on the row in the grid view below. A screen will appear with a further help tip explaining what to do next. Advanced users: Click 'Bulk Process' to download a CSV file - from here you can categorise your products en masse, and Advanced Help notes are provided on the Bulk Process screen.<br /><br />
		
		Once you have completed categorisation for each of the products you wish to categorise, go back to the Amazon menu and continue down the 'Advanced Setup' pull-out to the 'Field Mapping' page.
						</fieldset>
						
</div>
<?php } ?>