
<?php $_productCollection = $this->getItemCollection(); ?>
<?php // if($showBlock): ?>
	<div class="widget-static-block">
        <dl id="narrow-by-list2">
            <dt class="last odd"><h2>Top Sellers</h2></dt>
            <dd class="last odd">
        		<ol class="top-sellers">
<?php
foreach($_productCollection as $_product): ?>
            		<li>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a>
						<span class="top-price">$<?php echo number_format($_product->getFinalPrice(), 2, '.', '') ?></span>
            		</li>
<?php endforeach; ?>
        		</ol>
			</dd>
		</dl>
	</div>

<?php //endif; ?>




