<?php 

$inCartItems = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();
$_productCollection = array();
$limit = 5;
foreach ($inCartItems as $item){
    $product = $item->getProduct();

    $relatedItems = $product->getRelatedProductCollection()
		->addMinimalPrice()
		->addFinalPrice()
		->addTaxPercents()
		->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
		->addUrlRewrite()
		->addAttributeToSelect('required_options')
		->setPositionOrder()
		->addStoreFilter();

	foreach($relatedItems as $relatedItem) {
		$_productCollection[] = $relatedItem;
	} 
	$_collectionSize = count($_productCollection);
	$_columnCount = 5;
	$i = 0;
}

$_helper = $this->helper('catalog/output');
$productListBlock = $this->getLayout()->createBlock('catalog/product_list');
?>
<div class="category-products related-products">
	<h2>Related Products</h2>
	<?php foreach($_productCollection as $_product) : ?>
		<?php if ($i++%$_columnCount==0): ?>
        	<ul class="products-grid">
        <?php endif ?>
				<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<?php if ($productListBlock->helper('callouts')->getIsNew($_product)) : ?>
		                <div class="new-product-callout">New</div>
		            <?php endif ?> 
			        <?php if ($_product->getFinalPrice() < $_product->getPrice()) : ?>
			            <div class="sale-product-callout">On Sale</div>
			        <?php endif ?> 
		            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
		            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
		            <?php if($_product->getRatingSummary()): ?>
		            <?php echo $productListBlock->getReviewsSummaryHtml($_product, 'short') ?>
		            <?php endif; ?>
		            
		            	<?php $cfp = ($_product->getCallForPrice()) ? $_product->getCallForPrice() : Mage::getModel('catalog/product')->loadByAttribute('sku',$_product->getSku())->getCallForPrice(); ?>
		                <?php if($_product->isSaleable()): ?>
		            <?php echo $productListBlock->getPriceHtml($_product, true) ?>
		             <div class="actions">
		                   <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
		            </div>
		            <?php else: ?>
		                <div class="price-box"><span class="price"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('call_for_price')->toHTML();?></span></div>
		            <?php endif; ?>
			    </li>
		    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	        </ul><?php if($i < $limit) {echo '<hr/>';} else {break;} ?>
	        <?php endif ?>
	<?php endforeach; ?>
</div>
