
<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<div class="nav-container">
<?php /*
    <ul id="nav">
        <?php echo $_menu ?>
    </ul>
*/ ?>
<ul id="nav">
        <li class="level0 nav-1 level-top first parent">
		<a class="level-top" href="<?php echo $this->getUrl() ?>telecom-equipment"><span>Telecom Equipment</span></a>
	</li>

	<li class="level0 nav-2 level-top parent">
		<a class="level-top" href="<?php echo $this->getUrl() ?>pc-accessories"><span>Computer Accessories</span></a>
	</li>

	<li class="level0 nav-3 level-top parent">
		<a class="level-top" href="<?php echo $this->getUrl() ?>consumer-electronics"><span>Electronics</span></a>
	</li>
	<li class="level0 nav-4 level-top parent">
		<a class="level-top" href="<?php echo $this->getUrl() ?>hard-drives-storage"><span>Storage Solutions</span></a>
	</li>
	<?php /*
	<li class="level0 nav-5 level-top parent" id="Automotive">
		<a class="level-top" href="<?php echo $this->getUrl() ?>automotive"><span>Automotive</span></a>
	</li>
	*/ ?>
	<li class="level0 nav-5 level-top parent">
		<a class="level-top" href="<?php echo $this->getUrl() ?>newitems"><span>New Items</span></a>
	</li>
	<li class="level0 nav-6 level-top parent">
		<a class="level-top" href="<?php echo $this->getUrl() ?>clearance"><span>Clearance</span></a>
	</li>
</ul>
</div>
<?php endif ?>
