<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>


<div class="page-title">
	<br>
</div>

<div class="product-view" itemscope itemtype="http://schema.org/Product">
<h1 style="text-align:center;" itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
<br>
<div id="messages_product_view">
<?php echo $this->getMessagesBlock()->toHtml() ?>
</div>

    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
		
		<div>
        <div class="product-essential">
                <div class="product-shop">
                    <div class="product-main-info">
						<h3>Product Details</h3>
                        <p><?php echo $this->__('SKU# %s', $this->htmlEscape($_product->getSku())); ?></p>						
                        <p><?php echo $this->__('Retail Price $%s', $this->htmlEscape($_product->getMsrp ())); ?></p>						
                        <?php echo $this->getChildHtml('alert_urls') ?>
                        <?php echo $this->getChildHtml('product_type_data') ?>
						
                        <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
						
						
                    </div>
                    <?php echo $this->getChildHtml('tierprices') ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                    <?php echo $this->getChildHtml('product_reviews_action') ?>
					


                    <?php if (!$this->hasOptions()):?>
                        <div class="add-to-box">
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                            <?php echo $this->getChildHtml('addto') ?>
                        </div>
                    <?php else:?>
                        <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container1') ):?>
                            <div class="options-container-small">
                                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                            </div>
                        <?php endif;?>
                        <?php echo $this->getChildHtml('addto') ?>
                    <?php endif; ?>
					
					<div class="share">
						<?php if (strlen($_product->getData('share')) > 0) echo $_product->getData('share'); ?>
					</div>

                    <?php if ($_product->getShortDescription()):?>
                        <div class="short-description std" itemprop="description">
                            <h2><?php echo $this->__('Quick Overview') ?></h2>
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                        </div>
                    <?php endif;?>

                    <?php echo $this->getChildHtml('other');?>
                </div>
        </div>
        <div class="product-img-box">
        	<?php echo $this->getChildHtml('media') ?>
        </div>
		</div>
    </form>

        <div class="product-collateral">
            <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                <div id="collateral-tabs" class="collateral-tabs">
				<ul class="tabs">
                	<?php foreach ($detailedInfoGroup as $alias => $html):?><li class="tab" title="#<?php echo strtolower(str_replace(" ","_",$this->escapeHtml($this->getChildData($alias, 'title')))) ?>"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></li><?php endforeach;?>
					<?php if($_product->getTechSpecs()) : ?><li class="tab" title="#technical_specs"><span>Technical Specs</span></li><?php endif; ?>
                    <li class="tab" title="#reviews"><span>Reviews</span></li>
					<?php if($_product->getWarranty()) : ?><li class="tab" title="#warranty"><span>Warranty Info</span></li><?php endif; ?>
                    <li class="tab" title="#compatibility"><span>Compatibility</span></li>

				</ul>

                <?php foreach ($detailedInfoGroup as $alias => $html):?>
                    <div class="tab-container" id="<?php echo strtolower(str_replace(" ","_",$this->escapeHtml($this->getChildData($alias, 'title')))) ?>"><div class="tab-content"><?php echo $html ?></div></div>
                <?php endforeach;?>
				<?php if($_product->getTechSpecs()) : ?>
                    <div class="tab-container" id="technical_specs"><div class="tab-content"><?php echo $_product->getTechSpecs() ?></div></div>
				<?php endif; ?>
                    <div class="tab-container" id="reviews"><div class="tab-content"><?php echo $this->getChildHtml('product_reviews') ?></div></div>
				<?php if($_product->getWarranty()) : ?>
                    <div class="tab-container" id="warranty"><div class="tab-content"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('warranty_info')->toHTML();//$_product->getAttributeText('warranty') ?></div></div>
				<?php endif; ?>
                    <div class="tab-container" id="compatibility"><div class="tab-content"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('compatibility')->toHTML(); ?></div></div>
		</div>


                <script type="text/javascript">
				<!--
				//new Enterprise.Tabs('collateral-tabs')
				jQuery(document).ready(function() {

					jQuery(".tab-container").hide();
					jQuery("ul.tabs li:first").addClass("active").show();
					jQuery(".tab-container:first").show();

					jQuery("ul.tabs li").click(function() {
						switchTab(jQuery(this).attr("title"))
						return false;
					});
					
					jQuery("a[rel='tab']").click(function() {
						switchTab(jQuery(this).attr("href"))
						return false;
					});
				});
				function switchTab(tabId) {
					jQuery("ul.tabs li").removeClass("active");
					jQuery("ul.tabs li[title='"+tabId+"']").addClass("active");
					jQuery(".tab-container").hide();
					jQuery(tabId).fadeIn();
					return false;
				}
				
				
				-->
				</script>
				
            <?php endif; ?>
            <?php /* if ($this->canEmailToFriend()): ?>
                <p class="emailto-link"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; */ ?>
        </div>
        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildChildHtml('container2') ):?>
            <div class="options-container-big">
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            </div>
        <?php endif;?>
        <?php //echo $this->getChildHtml('relatedProducts') ?>
        <?php //echo $this->getChildHtml('productTagList') ?>
        <?php //echo $this->getChildHtml('product_additional_data') ?>
		<?php 
		if($_product->getDisclaimer()) :
		?>
		<div class="telecom-disclaimer">
		<?php echo $_product->getDisclaimer() ?>
		</div>
		<?php endif ?>
</div>


        <?php echo $this->getChildHtml('upsell_products') ?>


<script type="text/javascript">
//<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button) {
        if (this.validator.validate()) {
            this.form.submit();
            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);
//]]>
</script>
