<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container">
<?php /*
    <div class="header-panel">
        <div class="switches"><?php echo $this->getChildHtml('switches') ?></div>
        <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?></p>
        <?php echo $this->getChildHtml('accountLinks') ?>
    </div>
*/ ?>
    <div class="header">
        <div class="branding">
        <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        </div>
        <div >
            <?php /*<div class="checkout-link"><?php echo $this->getChildHtml('checkoutLinks') ?></div>*/ ?>
            <?php //echo $this->getChildHtml('topCart') ?>
            <div align="right"><?php echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('topSearch') ?></div>
        </div>
         <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?></p>
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php echo $this->getChildHtml('topContainer') ?>
</div>
