<?php $amazoncore = Mage::getModel('amazonimport/amazonimport'); ?>

<?php if(Mage::getStoreConfig('amazonint/general/hide_help_tips') == 0){ ?>
<div class="entry-edit">
    <div class="fieldset " id="group_fields4">
	<b>Help Tip:</b> This section allows you to tell Amazon the condition of your products. This is done to distinguish between 'New' and 'Used' items, for example.
	</div>
</div>
<?php } ?>

<div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Item Condition</h4>
    <div class="form-buttons"></div>
</div>
    <div class="fieldset " id="group_fields4">
    <div class="hor-scroll">
    	<div id="outputcondvalue">
             <center><b>Current Setting:</b> <?php echo $this->getCategoryCondition($this->getRequest()->getParam('id'), $amazoncore->loadSessionValue('camiloo_amazon_categorise_marketplace')); ?></center>
			 </div>
            </div>
        </div>
</div>
<?php if(Mage::getStoreConfig('amazonint/general/hide_help_tips') == 0){ ?>
<div class="entry-edit">
    <div class="fieldset " id="group_fields4">
	<b>Help Tip:</b>  If you wish, you may also enter a condition note below. This is optional, but may be used to specify information such as 'Factory Refurbished with new 3 year warranty'. Please do not use this space for marketing purposes, for example 'The Best Seller on Amazon!!' - This is against Amazon's Terms of Use and may result in your listings being removed.
	</div>
</div>
<?php } ?>

<div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Condition Note</h4>
    <div class="form-buttons"></div>
</div>
    <div class="fieldset " id="group_fields4">
    <div class="hor-scroll">
    	<div id="outputcnotevalue">
          <center><b>Current Setting:</b> <?php echo $this->getCategoryConditionNote($this->getRequest()->getParam('id'),$amazoncore->loadSessionValue('camiloo_amazon_categorise_marketplace')); ?></center></div>
            </div>
        </div>
        
</div>