<?php
$helper = Mage::helper('signaturelink');
$slData = $helper->getFlashParams();
$ieFlashUrl = $slData->flashFile . '?' . $slData->vars;
?>
<script type="text/javascript">
//jQuery(function() {
	sl_processDom('<?php echo $ieFlashUrl; ?>', '<?php echo $helper->generateSLSession(); ?>');
<?php if ($helper->isTCEnabled()): ?>
	sl_fetchTC('<?php echo $slData->clientId; ?>', '<?php echo $slData->storeId; ?>');
<?php endif; ?>
//});
</script>

<script type="text/javascript" rel="sljs">
//jQuery(function() {
	captureOptions.signPadOptions.signPadId = 'slpadConfirm';
	captureOptions.signPadOptions.readonly = true;

	var termsAndConditionsOptions = {
		use: false
	};
 
  cnps.init(captureOptions, termsAndConditionsOptions);
  cnps.registerSignpad();
//});
</script>
<center>
<div id="sl_pad_confirm" style="padding-top: 20px">
 <div id="slpadDivF9" class="slpadDivF9">
	<object id="slpadConfirmF9" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="400" height="200">
		<param name="movie" value="<?php echo $ieFlashUrl; ?>" />
		<param name="allowScriptAccess" value="always" />
		<!--[if !IE]>-->
		<object name="slpadConfirmF9" type="application/x-shockwave-flash" data="<?php echo $slData->flashFile; ?>" width="400" height="200">
			<param name="allowScriptAccess" value="always" />
			<param name="wmode" value="opaque" />
			<param name="FlashVars" value="<?php echo $slData->vars; ?>" />
		<!--[<![endif]-->
		<!-- p>You must have Flash installed to continue checkout.</p -->
		<!--[if !IE]>-->
		</object>
		<!--[<![endif]-->
	</object>
 </div>
	<div id="slpadDivH5" class="slpadDivH5">
		<canvas id="slpadConfirmH5" class="slsph5" height="171" width="301"></canvas>
		<a href="javascript:canvfuncs.undo();" id="slh5Undo">&nbsp;</a>
		<a href="javascript:canvfuncs.clear();" id="slh5Reset">&nbsp;</a>
		<a href="javascript:canvfuncs.showHelp();" id="slh5Help">&nbsp;</a>
	</div>

	<?php if ($helper->isTCEnabled()): ?>
	<div id="sl_tc_container">
		<div>PURCHASE AGREEMENT - Last Updated <span id="sl_tc_header"></span></div>
		<textarea id="sl_tc" rows="10" cols="100" style="min-width: 400px; width:99%;"></textarea>
	</div>
	<?php endif; ?>
</div>
</center>
