<?php $amazoncore = Mage::getModel('amazonimport/amazonimport'); ?>
<?php if($this->getRequest()->getParam('bn1') != ""){ ?>
<p class="grand-total">Step 5 of 6: Select an item type</p>
As well as using categories, Amazon classifies products into 'Item Types' to better help it to understand whether or not a product matches a customers search term. Therefore, please select an item from the list below which most closely describes your product. Once you have selected an option from the drop down list below, this wizard will move to the next step.
<br /><br />
<div style="width:90%;left:5%;position:absolute;padding-bottom:10px;">
<center><?php echo $this->getCategoryItemType($amazoncore->loadSessionValue('camiloo_amazon_categorise_marketplace')); ?></center>
</div>


<?php }else if($this->getData('complete') == true){ ?>
<script type='text/javascript'>
	var timer = setTimeout("hidePopover();",5000);
</script>
<p class="grand-total">Settings Saved</p>
Thank you. Your settings have been saved successfully. Please <a href="#" onclick='unset(timer);hidePopover();'>click here</a> or wait 5 seconds to continue.</a>

<?php }else{ ?>
<?php if(strlen($this->getCategoryVariationTheme($amazoncore->loadSessionValue('camiloo_amazon_categorise_marketplace'),true)) > 10){ ?>
<p class="grand-total">Step 6 of 6: Select Variation Theme</p>
The item type you have selected supports 'Variation Themes'. Think of a Variation Theme as a way of telling Amazon what products within this category could <i>potentially</i> vary by.<br /><br />
	
	The Amazon search engine is a very advanced system, and setting the Variation Theme helps to train it to suggest your product to potential customers. For example, if you sell a product simply titled '2 pack of Socks' but within a product attribute you tell Amazon that the socks are Red, it is the Variation Theme which connects these two pieces of Information and tells Amazon that the socks are Red. Setting the Variation Theme to 'Color' then, for example, allows Amazon to suggest your socks if a customer searches for 'Red Socks' over another retailers product named '2 pack of Socks' which happen to be blue. You may think of this as a search term tie-breaker question, perhaps.<br /><br />
	
	If you sell configurable or grouped products on Magento, set the below option to the type of product attributes your products are configurable by and the configurable product will appear on Amazon in a similar way - one product page for your product line with multiple options. So for example if you sell Jeans, these may come in different Sizes and Colours, and therefore you may choose Size Color from below. If you wish to skip this step, <a href="#" onclick="selectedVariationTheme('');">please click here</a>.
	<br /><br />
<div style="width:90%;left:5%;position:absolute;padding-bottom:10px;">
	<center><?php echo $this->getCategoryVariationTheme($amazoncore->loadSessionValue('camiloo_amazon_categorise_marketplace')); ?></center>
</div>
<?php }else{ ?>
<p class="grand-total">Step 6 of 6: Select Variation Theme</p>
There are no variation themes available for the product type you have selected. Skipping - please wait...
 <?php echo $this->getCategoryVariationTheme($amazoncore->loadSessionValue('camiloo_amazon_categorise_marketplace')); ?>

<?php } ?>


<?php } ?>