<div class="quote-create">
    <div class="page-title">
        <h1>Request a quote</h1>
    </div>
    <form enctype="multipart/form-data" id="form-validate" method="post" action="">
        <div class="fieldset">
            <h2 class="legend">Contact Information</h2>
            <ul class="form-list">
                <li>
                    <label class="required" for="title"><em>*</em>Quote Name</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" title="Title" value="" id="email_address" name="title"/>
                    </div>
                </li>
                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <label class="required" for="firstname"><em>*</em>First Name</label>
                            <div class="input-box">
                                <input type="text" class="input-text required-entry" maxlength="255" title="First Name" value="" name="firstname" id="firstname"/>
                            </div>
                        </div>
                        <div class="field name-lastname">
                            <label class="required" for="lastname"><em>*</em>Last Name</label>
                            <div class="input-box">
                                <input type="text" class="input-text required-entry" maxlength="255" title="Last Name" value="" name="lastname" id="lastname"/>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <label class="required" for="company"><em>*</em>Company</label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" title="Company" value="" id="email_address" name="company"/>
                    </div>
                </li>
                <li>
                    <label class="" for="phone">Phone #</label>
                    <div class="input-box">
                        <input type="text" class="input-text" title="Phone" value="" id="phone" name="phone"/>
                    </div>
                </li>
                <li>
                    <label class="required" for="email_address"><em>*</em>Email Address</label>
                    <div class="input-box">
                        <input type="text" class="input-text validate-email required-entry" title="Email Address" value="" id="email_address" name="email"/>
                    </div>
                </li>
            </ul>
        </div>
        
        <h2 class="legend">Item Inforamtion</h2>
        <br/>
        <?php echo $this->getChildHtml('list') ?>
        <br/>
        <div class="buttons-set form-buttons">
            <button title="Submit" class="button" type="submit" autocomplete="off"><span><span>Submit</span></span></button>
        </div>
        <p class="required">* Required Fields</p>
    </form>
    <script type="text/javascript">
    //&lt;![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]&gt;
    </script>
</div>
